/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.84
 * Generated at: 2022-12-21 08:50:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import jsbank.BPDAO;
import jsbank.BPDAO;

public final class bpadd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1671175422940L));
    _jspx_dependants.put("/bplist.jsp", Long.valueOf(1671510371987L));
    _jspx_dependants.put("jar:file:/C:/Users/kgitbank21/Desktop/진성/소프로젝트_JSBANK/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/jsbank/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1671611784913L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("jsbank.BPDAO");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
 request.setCharacterEncoding("UTF-8"); 
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f3(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("        nav {\r\n");
      out.write("            width: auto;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("        }\r\n");
      out.write("        ul, ol {\r\n");
      out.write("            list-style: none; \r\n");
      out.write("            padding-left: 0;\r\n");
      out.write("        }\r\n");
      out.write("        a.logo {\r\n");
      out.write("        	all: unset;\r\n");
      out.write("       		margin-right: auto;\r\n");
      out.write("       		cursor: pointer;\r\n");
      out.write("       	}\r\n");
      out.write("      \r\n");
      out.write("        a {\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: inherit;\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("        ul {\r\n");
      out.write("            background-color: #2085c1;\r\n");
      out.write("            display: flex;\r\n");
      out.write("        }\r\n");
      out.write("        ol {\r\n");
      out.write("            display: none;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 37px;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            width: 160px;\r\n");
      out.write("            background-color: #2085c1;\r\n");
      out.write("        }\r\n");
      out.write("        ul > li {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 35px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            border-bottom: 2px solid transparent;\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-family: 맑은 고딕;\r\n");
      out.write("        }\r\n");
      out.write("        ul > li:hover {\r\n");
      out.write("        	background-color: white;\r\n");
      out.write("            color: #2085c1; \r\n");
      out.write("        }\r\n");
      out.write("        ol > li > a {\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("            font-weight: normal;\r\n");
      out.write("            display: block;\r\n");
      out.write("            padding: 5px 10px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("        ol > li > a:hover {\r\n");
      out.write("            text-decoration: underline;\r\n");
      out.write("        }\r\n");
      out.write("        ul > li:hover > ol {\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .legend  {\r\n");
      out.write("        	font-size: 25px;\r\n");
      out.write("        	font-weight: bold;\r\n");
      out.write("        \r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        .scrolltable {\r\n");
      out.write("        	table-layout: fixed;\r\n");
      out.write("        	border-collapse: collapse;\r\n");
      out.write("        	border: 1px solid #888;\r\n");
      out.write("			width: auto;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("		.scrolltable th, .scrolltable td {\r\n");
      out.write("			padding: 10px;\r\n");
      out.write("			text-align: left;\r\n");
      out.write("			width: 100px;\r\n");
      out.write("			text-align: center;\r\n");
      out.write("			font-size: 0.875em;\r\n");
      out.write("		}\r\n");
      out.write("		.scrolltable tbody tr > td:nth-child(2n+1){\r\n");
      out.write("  			background-color: #e3f2fd;\r\n");
      out.write("		}\r\n");
      out.write("		.scrolltable thead {\r\n");
      out.write("		    display: block;\r\n");
      out.write("		    background: #8aacc8;\r\n");
      out.write("		    color: #fff;\r\n");
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("		.scrolltable tbody{\r\n");
      out.write("  			display: block;\r\n");
      out.write("   		    overflow: scroll;\r\n");
      out.write("    		height: 400px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		.scrolltable2 {\r\n");
      out.write("        	table-layout: fixed;\r\n");
      out.write("        	border-collapse:collapse;\r\n");
      out.write("        	border: 1px solid #888;\r\n");
      out.write("			width: auto;\r\n");
      out.write(" 			margin: auto;\r\n");
      out.write("        }\r\n");
      out.write("		.scrolltable2 th, .scrolltable2 td {\r\n");
      out.write("			padding: 10px;\r\n");
      out.write("			text-align: left;\r\n");
      out.write("			width: 100px;\r\n");
      out.write("			text-align: center;\r\n");
      out.write("			font-size: 0.875em;\r\n");
      out.write("		}\r\n");
      out.write("		.scrolltable2 tbody tr > td:nth-child(2n+1){\r\n");
      out.write("  			background-color: #e3f2fd;\r\n");
      out.write("		}\r\n");
      out.write("		.scrolltable2 thead {\r\n");
      out.write("		    display: block;\r\n");
      out.write("		    background: #8aacc8;\r\n");
      out.write("		    color:#fff;\r\n");
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("		.scrolltable2 tbody{\r\n");
      out.write("  			display: block;\r\n");
      out.write("   		    overflow: scroll;\r\n");
      out.write("    		height: 600px;\r\n");
      out.write("		}\r\n");
      out.write("		.emp {\r\n");
      out.write("			display: flex;\r\n");
      out.write("			align-items: center;\r\n");
      out.write("			justify-content: center;\r\n");
      out.write("		}\r\n");
      out.write(" 		.emp > form { \r\n");
      out.write(" 			position: relative;\r\n");
      out.write(" 			margin-right: 300px;		\r\n");
      out.write("			width: 20%;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		 .scrolltable3 {\r\n");
      out.write("        	table-layout: fixed;\r\n");
      out.write("        	border-collapse: collapse;\r\n");
      out.write("        	border: 1px solid #888;\r\n");
      out.write("			width: auto;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("		.scrolltable3 th, .scrolltable3 td {\r\n");
      out.write("			padding: 10px;\r\n");
      out.write("			text-align: left;\r\n");
      out.write("			width: 100px;\r\n");
      out.write("			text-align: center;\r\n");
      out.write("			font-size: 0.875em;\r\n");
      out.write("		}\r\n");
      out.write("		.scrolltable3 tbody tr > td:nth-child(2n+1){\r\n");
      out.write("  			background-color: #e3f2fd;\r\n");
      out.write("		}\r\n");
      out.write("		.scrolltable3 thead {\r\n");
      out.write("		    display: block;\r\n");
      out.write("		    background: #8aacc8;\r\n");
      out.write("		    color: #fff;\r\n");
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("		.scrolltable3 tbody{\r\n");
      out.write("  			display: block;\r\n");
      out.write("   		    overflow: scroll;\r\n");
      out.write("    		height: auto;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("		.scrolltable4 {\r\n");
      out.write("        	table-layout: fixed;\r\n");
      out.write("        	border-collapse: collapse;\r\n");
      out.write("        	border: 1px solid #888;\r\n");
      out.write("			width: auto;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("		.scrolltable4 th, .scrolltable4 td {\r\n");
      out.write("			padding: 10px;\r\n");
      out.write("			text-align: left;\r\n");
      out.write("			width: 100px;\r\n");
      out.write("			text-align: center;\r\n");
      out.write("			font-size: 0.875em;\r\n");
      out.write("		}\r\n");
      out.write("		.scrolltable4 tbody tr > td:nth-child(2n+1){\r\n");
      out.write("  			background-color: #e3f2fd;\r\n");
      out.write("		}\r\n");
      out.write("		.scrolltable4 thead {\r\n");
      out.write("		    display: block;\r\n");
      out.write("		    background: #8aacc8;\r\n");
      out.write("		    color: #fff;\r\n");
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("		.scrolltable4 tbody{\r\n");
      out.write("  			display: block;\r\n");
      out.write("   		    overflow: scroll;\r\n");
      out.write("    		height: 600px;\r\n");
      out.write("		}	\r\n");
      out.write("			\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header>\r\n");
      out.write("<a class=\"logo\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/logo2.jpg\" height=\"70px\"/></a>\r\n");
      out.write("    <nav>\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a>직원관리</a>\r\n");
      out.write("                 <ol>\r\n");
      out.write("                    <li><a href=\"emplist.jsp\">직원 목록</a></li>\r\n");
      out.write("                    <li><a href=\"empadd.jsp\">직원 추가</a></li>\r\n");
      out.write("                    <li><a href=\"empmodify.jsp\">직원 수정/삭제</a></li>                  \r\n");
      out.write("                </ol>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a>고객관리</a>\r\n");
      out.write("                <ol>\r\n");
      out.write("                    <li><a href=\"clilist.jsp\">고객 목록</a></li>\r\n");
      out.write("                    <li><a href=\"cliadd.jsp\">고객 추가</a></li>\r\n");
      out.write("                    <li><a href=\"climodify.jsp\">고객 수정/삭제</a></li>                    \r\n");
      out.write("                </ol>\r\n");
      out.write("            </li>\r\n");
      out.write("         \r\n");
      out.write("            <li>\r\n");
      out.write("                <a>상품관리</a>\r\n");
      out.write("                <ol>\r\n");
      out.write("                    <li><a href=\"bplist.jsp\">상품 목록</a></li>\r\n");
      out.write("                    <li><a href=\"bpadd.jsp\">상품 추가</a></li>\r\n");
      out.write("                    <li><a href=\"bpmodify.jsp\">상품 수정/삭제</a></li>\r\n");
      out.write("                </ol>\r\n");
      out.write("            </li>\r\n");
      out.write("  \r\n");
      out.write("            <li>\r\n");
      out.write("                <a>판매</a>\r\n");
      out.write("                <ol>\r\n");
      out.write("                    <li><a href=\"saleAllList.jsp\">전체 판매 목록</a></li>\r\n");
      out.write("                    <li><a href=\"saleMonthList.jsp\">월별 판매 목록</a></li>\r\n");
      out.write("                    <li><a href=\"saleYearList.jsp\">연도별 판매 목록</a></li>\r\n");
      out.write("                    <li><a href=\"saleBpList.jsp\">상품별 판매 목록</a></li>\r\n");
      out.write("                </ol>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"index.jsp\">스케줄 관리</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"\">회계</a>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("	</nav>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table class=\"scrolltable\">\r\n");
      out.write("	<thead>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th style=\"width:60px\">상품번호</th>\r\n");
      out.write("			<th style=\"width:130px\">상품이름</th>\r\n");
      out.write("			<th>가입조건</th>\r\n");
      out.write("			<th>가입기간</th>\r\n");
      out.write("			<th>세전이자율</th>\r\n");
      out.write("			<th>최대우대금리</th>\r\n");
      out.write("			<th style=\"width:40px\">변동</th>\r\n");
      out.write("			<th style=\"width:250px\">비고</th>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</thead>\r\n");
      out.write("	<tbody>\r\n");
      out.write("	");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	</tbody>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("<form method=\"POST\" action=\"bpadd-action.jsp\">\r\n");
      out.write("<fieldset style=\"width:850px\">\r\n");
      out.write("<legend class=\"legend\">상품 추가</legend>\r\n");
      out.write("<p>상품명 : <input type=\"text\" name=\"bpname\" placeholder=\"이름\" required autofocus>\r\n");
      out.write("	가입조건 : 	\r\n");
      out.write("		<select name=\"regcon\" required>\r\n");
      out.write("			<option value=\"\">==선택하세요 (1~10등급)==</option>\r\n");
      out.write("			<option>1등급이상</option>\r\n");
      out.write("			<option>2등급이상</option>\r\n");
      out.write("			<option>3등급이상</option>\r\n");
      out.write("			<option>4등급이상</option>\r\n");
      out.write("			<option>5등급이상</option>\r\n");
      out.write("			<option>6등급이상</option>\r\n");
      out.write("			<option>7등급이상</option>\r\n");
      out.write("			<option>8등급이상</option>\r\n");
      out.write("			<option>9등급이상</option>\r\n");
      out.write("			<option>10등급이상</option>\r\n");
      out.write("		</select>\r\n");
      out.write("	\r\n");
      out.write("	가입기간 : \r\n");
      out.write("		<select name=\"period\" required>\r\n");
      out.write("			<option value=\"\">==선택하세요==</option>\r\n");
      out.write("			<option>1년</option>\r\n");
      out.write("			<option>2년</option>\r\n");
      out.write("			<option>3년</option>\r\n");
      out.write("			<option>4년</option>\r\n");
      out.write("			<option>5년이상</option>\r\n");
      out.write("		</select>\r\n");
      out.write("</p>\r\n");
      out.write("<p>세전이자율 : <input type=\"text\" name=\"taxrate\" placeholder=\"세전이자율\" required>\r\n");
      out.write("	최대우대금리 : <input type=\"text\" name=\"maxrate\" placeholder=\"최대우대금리\" required >\r\n");
      out.write("	변동 : <input type=\"text\" name=\"wave\" placeholder=\"변동\">\r\n");
      out.write("	</p>\r\n");
      out.write("<p>비고 : <input type=\"text\" name=\"note\" placeholder=\"비고\"></p>\r\n");
      out.write("<p><input style=\"width:70px; height:40px; font-size:15px; font-weight:bold;\" type=\"submit\" value=\"추가\"></p>\r\n");
      out.write("	\r\n");
      out.write("</fieldset>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /header.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("cpath");
      // /header.jsp(5,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /header.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("dao");
      // /header.jsp(6,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${EmpDAO.getInstance() }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f2_reused = false;
    try {
      _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f2.setParent(null);
      // /header.jsp(7,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setVar("dao2");
      // /header.jsp(7,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${CliDAO.getInstance() }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
      if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      _jspx_th_c_005fset_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f3 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f3_reused = false;
    try {
      _jspx_th_c_005fset_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f3.setParent(null);
      // /header.jsp(8,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f3.setVar("dao3");
      // /header.jsp(8,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BPDAO.getInstance() }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f3 = _jspx_th_c_005fset_005f3.doStartTag();
      if (_jspx_th_c_005fset_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f3);
      _jspx_th_c_005fset_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f4 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f4_reused = false;
    try {
      _jspx_th_c_005fset_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f4.setParent(null);
      // /header.jsp(9,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f4.setVar("dao4");
      // /header.jsp(9,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f4.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SaleDAO.getInstance() }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f4 = _jspx_th_c_005fset_005f4.doStartTag();
      if (_jspx_th_c_005fset_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f4);
      _jspx_th_c_005fset_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /bplist.jsp(20,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("dto");
      // /bplist.jsp(20,1) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dao3.selectList() }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("		<tr>\r\n");
            out.write("			<td style=\"width:60px\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.bpno }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("			<td style=\"width:130px\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.bpname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("			<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.regcon }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("			<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.period }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("			<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.taxrate }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("%</td>\r\n");
            out.write("			<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.maxrate }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("%</td>\r\n");
            out.write("			<td style=\"width:40px\" >");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.wave }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("%</td>\r\n");
            out.write("			<td style=\"width:250px\" >");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.note }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("		</tr>\r\n");
            out.write("	");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
