/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.84
 * Generated at: 2022-12-21 09:03:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1671175422940L));
    _jspx_dependants.put("jar:file:/C:/Users/kgitbank21/Desktop/진성/소프로젝트_JSBANK/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/jsbank/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1671611784913L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
 request.setCharacterEncoding("UTF-8"); 
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f3(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("        nav {\r\n");
      out.write("            width: auto;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("        }\r\n");
      out.write("        ul, ol {\r\n");
      out.write("            list-style: none; \r\n");
      out.write("            padding-left: 0;\r\n");
      out.write("        }\r\n");
      out.write("        a.logo {\r\n");
      out.write("        	all: unset;\r\n");
      out.write("       		margin-right: auto;\r\n");
      out.write("       		cursor: pointer;\r\n");
      out.write("       	}\r\n");
      out.write("      \r\n");
      out.write("        a {\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: inherit;\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("        ul {\r\n");
      out.write("            background-color: #2085c1;\r\n");
      out.write("            display: flex;\r\n");
      out.write("        }\r\n");
      out.write("        ol {\r\n");
      out.write("            display: none;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 37px;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            width: 160px;\r\n");
      out.write("            background-color: #2085c1;\r\n");
      out.write("        }\r\n");
      out.write("        ul > li {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 35px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            border-bottom: 2px solid transparent;\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-family: 맑은 고딕;\r\n");
      out.write("        }\r\n");
      out.write("        ul > li:hover {\r\n");
      out.write("        	background-color: white;\r\n");
      out.write("            color: #2085c1; \r\n");
      out.write("        }\r\n");
      out.write("        ol > li > a {\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("            font-weight: normal;\r\n");
      out.write("            display: block;\r\n");
      out.write("            padding: 5px 10px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("        ol > li > a:hover {\r\n");
      out.write("            text-decoration: underline;\r\n");
      out.write("        }\r\n");
      out.write("        ul > li:hover > ol {\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .legend  {\r\n");
      out.write("        	font-size: 25px;\r\n");
      out.write("        	font-weight: bold;\r\n");
      out.write("        \r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        .scrolltable {\r\n");
      out.write("        	table-layout: fixed;\r\n");
      out.write("        	border-collapse: collapse;\r\n");
      out.write("        	border: 1px solid #888;\r\n");
      out.write("			width: auto;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("		.scrolltable th, .scrolltable td {\r\n");
      out.write("			padding: 10px;\r\n");
      out.write("			text-align: left;\r\n");
      out.write("			width: 100px;\r\n");
      out.write("			text-align: center;\r\n");
      out.write("			font-size: 0.875em;\r\n");
      out.write("		}\r\n");
      out.write("		.scrolltable tbody tr > td:nth-child(2n+1){\r\n");
      out.write("  			background-color: #e3f2fd;\r\n");
      out.write("		}\r\n");
      out.write("		.scrolltable thead {\r\n");
      out.write("		    display: block;\r\n");
      out.write("		    background: #8aacc8;\r\n");
      out.write("		    color: #fff;\r\n");
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("		.scrolltable tbody{\r\n");
      out.write("  			display: block;\r\n");
      out.write("   		    overflow: scroll;\r\n");
      out.write("    		height: 400px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		.scrolltable2 {\r\n");
      out.write("        	table-layout: fixed;\r\n");
      out.write("        	border-collapse:collapse;\r\n");
      out.write("        	border: 1px solid #888;\r\n");
      out.write("			width: auto;\r\n");
      out.write(" 			margin: auto;\r\n");
      out.write("        }\r\n");
      out.write("		.scrolltable2 th, .scrolltable2 td {\r\n");
      out.write("			padding: 10px;\r\n");
      out.write("			text-align: left;\r\n");
      out.write("			width: 100px;\r\n");
      out.write("			text-align: center;\r\n");
      out.write("			font-size: 0.875em;\r\n");
      out.write("		}\r\n");
      out.write("		.scrolltable2 tbody tr > td:nth-child(2n+1){\r\n");
      out.write("  			background-color: #e3f2fd;\r\n");
      out.write("		}\r\n");
      out.write("		.scrolltable2 thead {\r\n");
      out.write("		    display: block;\r\n");
      out.write("		    background: #8aacc8;\r\n");
      out.write("		    color:#fff;\r\n");
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("		.scrolltable2 tbody{\r\n");
      out.write("  			display: block;\r\n");
      out.write("   		    overflow: scroll;\r\n");
      out.write("    		height: 600px;\r\n");
      out.write("		}\r\n");
      out.write("		.emp {\r\n");
      out.write("			display: flex;\r\n");
      out.write("			align-items: center;\r\n");
      out.write("			justify-content: center;\r\n");
      out.write("		}\r\n");
      out.write(" 		.emp > form { \r\n");
      out.write(" 			position: relative;\r\n");
      out.write(" 			margin-right: 300px;		\r\n");
      out.write("			width: 20%;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		 .scrolltable3 {\r\n");
      out.write("        	table-layout: fixed;\r\n");
      out.write("        	border-collapse: collapse;\r\n");
      out.write("        	border: 1px solid #888;\r\n");
      out.write("			width: auto;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("		.scrolltable3 th, .scrolltable3 td {\r\n");
      out.write("			padding: 10px;\r\n");
      out.write("			text-align: left;\r\n");
      out.write("			width: 100px;\r\n");
      out.write("			text-align: center;\r\n");
      out.write("			font-size: 0.875em;\r\n");
      out.write("		}\r\n");
      out.write("		.scrolltable3 tbody tr > td:nth-child(2n+1){\r\n");
      out.write("  			background-color: #e3f2fd;\r\n");
      out.write("		}\r\n");
      out.write("		.scrolltable3 thead {\r\n");
      out.write("		    display: block;\r\n");
      out.write("		    background: #8aacc8;\r\n");
      out.write("		    color: #fff;\r\n");
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("		.scrolltable3 tbody{\r\n");
      out.write("  			display: block;\r\n");
      out.write("   		    overflow: scroll;\r\n");
      out.write("    		height: auto;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("		.scrolltable4 {\r\n");
      out.write("        	table-layout: fixed;\r\n");
      out.write("        	border-collapse: collapse;\r\n");
      out.write("        	border: 1px solid #888;\r\n");
      out.write("			width: auto;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("		.scrolltable4 th, .scrolltable4 td {\r\n");
      out.write("			padding: 10px;\r\n");
      out.write("			text-align: left;\r\n");
      out.write("			width: 100px;\r\n");
      out.write("			text-align: center;\r\n");
      out.write("			font-size: 0.875em;\r\n");
      out.write("		}\r\n");
      out.write("		.scrolltable4 tbody tr > td:nth-child(2n+1){\r\n");
      out.write("  			background-color: #e3f2fd;\r\n");
      out.write("		}\r\n");
      out.write("		.scrolltable4 thead {\r\n");
      out.write("		    display: block;\r\n");
      out.write("		    background: #8aacc8;\r\n");
      out.write("		    color: #fff;\r\n");
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("		.scrolltable4 tbody{\r\n");
      out.write("  			display: block;\r\n");
      out.write("   		    overflow: scroll;\r\n");
      out.write("    		height: 600px;\r\n");
      out.write("		}	\r\n");
      out.write("			\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header>\r\n");
      out.write("<a class=\"logo\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/logo2.jpg\" height=\"70px\"/></a>\r\n");
      out.write("    <nav>\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a>직원관리</a>\r\n");
      out.write("                 <ol>\r\n");
      out.write("                    <li><a href=\"emplist.jsp\">직원 목록</a></li>\r\n");
      out.write("                    <li><a href=\"empadd.jsp\">직원 추가</a></li>\r\n");
      out.write("                    <li><a href=\"empmodify.jsp\">직원 수정/삭제</a></li>                  \r\n");
      out.write("                </ol>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a>고객관리</a>\r\n");
      out.write("                <ol>\r\n");
      out.write("                    <li><a href=\"clilist.jsp\">고객 목록</a></li>\r\n");
      out.write("                    <li><a href=\"cliadd.jsp\">고객 추가</a></li>\r\n");
      out.write("                    <li><a href=\"climodify.jsp\">고객 수정/삭제</a></li>                    \r\n");
      out.write("                </ol>\r\n");
      out.write("            </li>\r\n");
      out.write("         \r\n");
      out.write("            <li>\r\n");
      out.write("                <a>상품관리</a>\r\n");
      out.write("                <ol>\r\n");
      out.write("                    <li><a href=\"bplist.jsp\">상품 목록</a></li>\r\n");
      out.write("                    <li><a href=\"bpadd.jsp\">상품 추가</a></li>\r\n");
      out.write("                    <li><a href=\"bpmodify.jsp\">상품 수정/삭제</a></li>\r\n");
      out.write("                </ol>\r\n");
      out.write("            </li>\r\n");
      out.write("  \r\n");
      out.write("            <li>\r\n");
      out.write("                <a>판매</a>\r\n");
      out.write("                <ol>\r\n");
      out.write("                    <li><a href=\"saleAllList.jsp\">전체 판매 목록</a></li>\r\n");
      out.write("                    <li><a href=\"saleMonthList.jsp\">월별 판매 목록</a></li>\r\n");
      out.write("                    <li><a href=\"saleYearList.jsp\">연도별 판매 목록</a></li>\r\n");
      out.write("                    <li><a href=\"saleBpList.jsp\">상품별 판매 목록</a></li>\r\n");
      out.write("                </ol>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"index.jsp\">스케줄 관리</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"\">회계</a>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("	</nav>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".cal_top {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	font-size: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cal {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table.calendar {\r\n");
      out.write("	border: 1px solid black;\r\n");
      out.write("	display: inline-table;\r\n");
      out.write("	text-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table.calendar td {\r\n");
      out.write("	vertical-align: top;\r\n");
      out.write("	border: 1px solid skyblue;\r\n");
      out.write("	width: 100px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<div class=\"cal_top\">\r\n");
      out.write("	<a href=\"#\" id=\"movePrevMonth\"><span id=\"prevMonth\" class=\"cal_tit\">&lt;</span></a>\r\n");
      out.write("	<span id=\"cal_top_year\"></span> <span id=\"cal_top_month\"></span> <a\r\n");
      out.write("		href=\"#\" id=\"moveNextMonth\"><span id=\"nextMonth\" class=\"cal_tit\">&gt;</span></a>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"cal_tab\" class=\"cal\"></div>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	var today = null;\r\n");
      out.write("	var year = null;\r\n");
      out.write("	var month = null;\r\n");
      out.write("	var firstDay = null;\r\n");
      out.write("	var lastDay = null;\r\n");
      out.write("	var $tdDay = null;\r\n");
      out.write("	var $tdSche = null;\r\n");
      out.write("	var jsonData = null;\r\n");
      out.write("	$(document).ready(function() {\r\n");
      out.write("		drawCalendar();\r\n");
      out.write("		initDate();\r\n");
      out.write("		drawDays();\r\n");
      out.write("		drawSche();\r\n");
      out.write("		$(\"#movePrevMonth\").on(\"click\", function() {\r\n");
      out.write("			movePrevMonth();\r\n");
      out.write("		});\r\n");
      out.write("		$(\"#moveNextMonth\").on(\"click\", function() {\r\n");
      out.write("			moveNextMonth();\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	//Calendar 그리기\r\n");
      out.write("	function drawCalendar() {\r\n");
      out.write("		var setTableHTML = \"\";\r\n");
      out.write("		setTableHTML += '<table class=\"calendar\">';\r\n");
      out.write("		setTableHTML += '<tr><th>SUN</th><th>MON</th><th>TUE</th><th>WED</th><th>THU</th><th>FRI</th><th>SAT</th></tr>';\r\n");
      out.write("		for (var i = 0; i < 6; i++) {\r\n");
      out.write("			setTableHTML += '<tr height=\"100\">';\r\n");
      out.write("			for (var j = 0; j < 7; j++) {\r\n");
      out.write("				setTableHTML += '<td style=\"text-overflow:ellipsis;overflow:hidden;white-space:nowrap\">';\r\n");
      out.write("				setTableHTML += '    <div class=\"cal-day\"></div>';\r\n");
      out.write("				setTableHTML += '    <div class=\"cal-schedule\"></div>';\r\n");
      out.write("				setTableHTML += '</td>';\r\n");
      out.write("			}\r\n");
      out.write("			setTableHTML += '</tr>';\r\n");
      out.write("		}\r\n");
      out.write("		setTableHTML += '</table>';\r\n");
      out.write("		$(\"#cal_tab\").html(setTableHTML);\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	//날짜 초기화\r\n");
      out.write("	function initDate() {\r\n");
      out.write("		$tdDay = $(\"td div.cal-day\")\r\n");
      out.write("		$tdSche = $(\"td div.cal-schedule\")\r\n");
      out.write("		dayCount = 0;\r\n");
      out.write("		today = new Date();\r\n");
      out.write("		year = today.getFullYear();\r\n");
      out.write("		month = today.getMonth() + 1;\r\n");
      out.write("		if (month < 10) {\r\n");
      out.write("			month = \"0\" + month;\r\n");
      out.write("		}\r\n");
      out.write("		firstDay = new Date(year, month - 1, 1);\r\n");
      out.write("		lastDay = new Date(year, month, 0);\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	//calendar 날짜표시\r\n");
      out.write("	function drawDays() {\r\n");
      out.write("		$(\"#cal_top_year\").text(year);\r\n");
      out.write("		$(\"#cal_top_month\").text(month);\r\n");
      out.write("		for (var i = firstDay.getDay(); i < firstDay.getDay()\r\n");
      out.write("				+ lastDay.getDate(); i++) {\r\n");
      out.write("			$tdDay.eq(i).text(++dayCount);\r\n");
      out.write("		}\r\n");
      out.write("		for (var i = 0; i < 42; i += 7) {\r\n");
      out.write("			$tdDay.eq(i).css(\"color\", \"red\");\r\n");
      out.write("		}\r\n");
      out.write("		for (var i = 6; i < 42; i += 7) {\r\n");
      out.write("			$tdDay.eq(i).css(\"color\", \"blue\");\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	//calendar 월 이동\r\n");
      out.write("	function movePrevMonth() {\r\n");
      out.write("		month--;\r\n");
      out.write("		if (month <= 0) {\r\n");
      out.write("			month = 12;\r\n");
      out.write("			year--;\r\n");
      out.write("		}\r\n");
      out.write("		if (month < 10) {\r\n");
      out.write("			month = String(\"0\" + month);\r\n");
      out.write("		}\r\n");
      out.write("		getNewInfo();\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function moveNextMonth() {\r\n");
      out.write("		month++;\r\n");
      out.write("		if (month > 12) {\r\n");
      out.write("			month = 1;\r\n");
      out.write("			year++;\r\n");
      out.write("		}\r\n");
      out.write("		if (month < 10) {\r\n");
      out.write("			month = String(\"0\" + month);\r\n");
      out.write("		}\r\n");
      out.write("		getNewInfo();\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	//정보갱신\r\n");
      out.write("	function getNewInfo() {\r\n");
      out.write("		for (var i = 0; i < 42; i++) {\r\n");
      out.write("			$tdDay.eq(i).text(\"\");\r\n");
      out.write("			$tdSche.eq(i).text(\"\");\r\n");
      out.write("		}\r\n");
      out.write("		dayCount = 0;\r\n");
      out.write("		firstDay = new Date(year, month - 1, 1);\r\n");
      out.write("		lastDay = new Date(year, month, 0);\r\n");
      out.write("		drawDays();\r\n");
      out.write("		drawSche();\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	//2019-08-27 추가본\r\n");
      out.write("\r\n");
      out.write("	//데이터 등록\r\n");
      out.write("	function setData() {\r\n");
      out.write("		jsonData = {\r\n");
      out.write("			\"2022\" : {\r\n");
      out.write("				\"12\" : {\r\n");
      out.write("					\"22\" : \"지리는발표일\",\r\n");
      out.write("					\"23\" : \"시험일\",\r\n");
      out.write("					\"25\" : \"메리크리스마스\"\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	//스케줄 그리기\r\n");
      out.write("	function drawSche() {\r\n");
      out.write("		setData();\r\n");
      out.write("		var dateMatch = null;\r\n");
      out.write("		for (var i = firstDay.getDay(); i < firstDay.getDay()\r\n");
      out.write("				+ lastDay.getDate(); i++) {\r\n");
      out.write("			var txt = \"\";\r\n");
      out.write("			txt = jsonData[year];\r\n");
      out.write("			if (txt) {\r\n");
      out.write("				txt = jsonData[year][month];\r\n");
      out.write("				if (txt) {\r\n");
      out.write("					txt = jsonData[year][month][i];\r\n");
      out.write("					dateMatch = firstDay.getDay() + i - 1;\r\n");
      out.write("					$tdSche.eq(dateMatch).text(txt);\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /header.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("cpath");
      // /header.jsp(5,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /header.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("dao");
      // /header.jsp(6,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${EmpDAO.getInstance() }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f2_reused = false;
    try {
      _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f2.setParent(null);
      // /header.jsp(7,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setVar("dao2");
      // /header.jsp(7,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${CliDAO.getInstance() }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
      if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      _jspx_th_c_005fset_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f3 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f3_reused = false;
    try {
      _jspx_th_c_005fset_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f3.setParent(null);
      // /header.jsp(8,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f3.setVar("dao3");
      // /header.jsp(8,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BPDAO.getInstance() }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f3 = _jspx_th_c_005fset_005f3.doStartTag();
      if (_jspx_th_c_005fset_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f3);
      _jspx_th_c_005fset_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f4 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f4_reused = false;
    try {
      _jspx_th_c_005fset_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f4.setParent(null);
      // /header.jsp(9,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f4.setVar("dao4");
      // /header.jsp(9,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f4.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SaleDAO.getInstance() }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f4 = _jspx_th_c_005fset_005f4.doStartTag();
      if (_jspx_th_c_005fset_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f4);
      _jspx_th_c_005fset_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f4_reused);
    }
    return false;
  }
}
